server:
  port: 8081
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:  health
  endpoint:
    metrics:
      enabled: true
spring:
  data:
    mongodb:
      #uri: mongodb://localhost:27017/demo
      uri: ${MONGO_URL}
     
      